_wandb:
    value:
        cli_version: 0.22.3
        e:
            qrchx7x1a326b9o2jaq0dfqi7yk95yr9:
                codePath: milestone2/feature_engineering.py
                codePathLocal: milestone2/feature_engineering.py
                cpu_count: 14
                cpu_count_logical: 20
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "498590711808"
                        used: "90603597824"
                email: abdelhamid.rouatbi@umontreal.ca
                executable: /home/moonette/miniconda3/envs/proj1/bin/python
                git:
                    commit: c9e14dc0db5d49ecf5cf27d18c9d03713d065277
                    remote: https://github.com/AbdelhamidRouatbi/data-science-code.git
                gpu: NVIDIA GeForce RTX 3060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 3840
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce RTX 3060 Laptop GPU
                      uuid: GPU-dde1b2e8-aa71-aeee-573f-356252eb8325
                host: Noveria
                memory:
                    total: "16430759936"
                os: Linux-6.17.7-arch1-1-x86_64-with-glibc2.42
                program: /home/moonette/Academia/courses/data_science/project/project/data-science-code/milestone2/feature_engineering.py
                python: CPython 3.13.5
                root: /home/moonette/Academia/courses/data_science/project/project/data-science-code
                startedAt: "2025-11-12T04:54:07.244325Z"
                writerId: qrchx7x1a326b9o2jaq0dfqi7yk95yr9
        m: []
        python_version: 3.13.5
        t:
            "4": 3.13.5
            "5": 0.22.3
            "12": 0.22.3
            "13": linux-x86_64
